In [1]:
# Install if you have never used these: unblock the lines below to install if needed

#!pip install webdriver-manager
#!pip3 install lxml
#!pip3 install selenium
#!pip3 install webdriver_manager
#!pip install --upgrade pip
#!pip install -U selenium

In [2]:
# --------- import necessary modules -------

# For webscraping
from bs4 import BeautifulSoup

# Parsing and creating xml data
from lxml import etree as et

# Store data as a csv file written out
from csv import writer

# In general to use with timing our function calls to Indeed
import time

# Assist with creating incremental timing for our scraping to seem more human
from time import sleep

# Dataframe stuff
import pandas as pd

# Random integer for more realistic timing for clicks, buttons and searches during scraping
from random import randint

# Multi Threading
import threading

# Threading:
from concurrent.futures import ThreadPoolExecutor, wait

In [3]:
import selenium

# Check version I am running
selenium.__version__

'4.19.0'

In [4]:
# Selenium 4:

from selenium import webdriver

# Starting/Stopping Driver: can specify ports or location but not remote access
from selenium.webdriver.chrome.service import Service as ChromeService

# Manages Binaries needed for WebDriver without installing anything directly
from webdriver_manager.chrome import ChromeDriverManager

In [5]:
# Allows searchs similar to beautiful soup: find_all
from selenium.webdriver.common.by import By

# Try to establish wait times for the page to load
from selenium.webdriver.support.ui import WebDriverWait

# Wait for specific condition based on defined task: web elements, boolean are examples
from selenium.webdriver.support import expected_conditions as EC

# Used for keyboard movements, up/down, left/right,delete, etc
from selenium.webdriver.common.keys import Keys

# Locate elements on page and throw error if they do not exist
from selenium.common.exceptions import NoSuchElementException

In [7]:
import csv
from time import sleep
from random import randint
from datetime import datetime

job_ = ['business+analyst','data+analyst','software+engineer']
loc = 'Singapore'

paginaton_url_ = 'https://sg.indeed.com/jobs?q={}&l={}&sort=date&start={}'

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
p_ = []
salary_list_ = []
company_list_ = []
location_list_ = []
job_description_list_ = []
posted_date_list_ = []
url_list_ = []

# Loop through each job and location combination
for job in job_:
    for i in range(0, 7):  # Scrape 7 pages for each job for latest job postings
        driver.get(paginaton_url_.format(job, loc, i * 10))
        sleep(randint(2, 5))

        # Scroll through the page and obtain job listings one by one
        job_page = driver.find_element(By.ID, "mosaic-jobResults")
        jobs = job_page.find_elements(By.CLASS_NAME, "job_seen_beacon")

        for idx, jj in enumerate(jobs):
                    try:
                        # Scroll to the current job listing
                        driver.execute_script("arguments[0].scrollIntoView(true);", jj)
                        sleep(1)

                        # Click on the job listing
                        jj.click()
                        sleep(2)  # Add a short pause after clicking

                    except:
                        close_button = driver.find_element(By.CSS_SELECTOR, "button[aria-label='close']")
                        close_button.click()
                        sleep(1)  # Add a short pause after closing the pop-up

                    # job title
                    try:
                        job_title = driver.find_element(By.CLASS_NAME, "jobsearch-JobInfoHeader-title-container").text
                        p_.append(job_title)
                    except:
                        p_.append(None)
                        
                    # salary
                    try:
                        salary = driver.find_element(By.CSS_SELECTOR, "div[data-testid='jobsearch-OtherJobDetailsContainer']").text
                        salary_list_.append(salary)
                    except:
                        salary_list_.append(None)
            

                    # company name
                    try:
                        company = driver.find_element(By.CSS_SELECTOR, "div[data-testid='inlineHeader-companyName']").text
                        company_list_.append(company)
                    except:
                        company_list_.append(None)    

                    # company location
                    try:
                        location = driver.find_element(By.CSS_SELECTOR, "div[data-testid='inlineHeader-companyLocation']").text
                        location_list_.append(location)
                    except:
                        location_list_.append(None)

                    # job description
                    try:
                        job_description = driver.find_element(By.ID, "jobDescriptionText").text
                        job_description_list_.append(job_description)
                    except:
                        job_description_list_.append(None)
                    
                    # posting date
                    try:
                        posted_date_element = driver.find_element(By.CSS_SELECTOR, "span[data-testid='myJobsStateDate']")
                        posted_date = posted_date_element.get_attribute("textContent")
                        posted_date_list_.append(posted_date)
                    except:
                        posted_date_list_.append(None)
                    
                    # URL
                    try:
                        job_url = driver.current_url
                        url_list_.append(job_url)
                    except:
                        url_list_.append(None)
                    
            
driver.quit()

# Write data to CSV file
with open('indeed_jobs_raw.csv', 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['Job Title', 'Company', 'Salary', 'Job Type', 'Location', 'Job Description', 'Posted Date Raw', 'Today Date', 'Job Posting Date','URL']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    today_date = datetime.now()
    today_date = today_date.strftime("%d/%m/%Y")
    
    writer.writeheader()
    for job, company, salary, location, job_description, posted_date, url in zip(p_, company_list_, salary_list_, location_list_, job_description_list_, posted_date_list_, url_list_):
        writer.writerow({'Job Title': job, 'Company': company, 'Salary': salary, 'Location': location, 'Job Description': job_description, 'Posted Date Raw': posted_date, 'Today Date': today_date, 'URL': url})

## PREPROCESSING FOR INDEED

In [34]:
data = pd.read_csv('indeed_jobs_raw.csv')
data

,Job Title,Company,Salary,Job Type,Location,Job Description,Posted Date Raw,Today Date,Job Posting Date,URL
0,Business Analyst\n- job post,EMQ2 TECHNOLOGY SERVICES PTE. LTD.,"$5,400 - $7,500 a month - Full-time",NaN,Singapore,Main Activities and Tasks\nOrganize and facili...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
1,Business Analyst\n- job post,ITCAN PTE. LIMITED,"$5,000 - $7,000 a month - Full-time",NaN,Singapore,Mandatory Skills Overview: As a Business Analy...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
2,Business Analyst\n- job post,TECHNOPALS CONSULTANTS PTE. LTD.,"$6,000 - $7,500 a month - Contract",NaN,Singapore,Mandatory Skills\nOverview :\nAs a Business An...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
3,Business Analyst |Up to $9500 |East\n- job post,JULIAN GREY CORPORATE ADVISORY PTE. LTD.,"$7,000 - $9,500 a month - Permanent, Full-time",NaN,Singapore,Company’s Profile\nJulian Grey’s client is a s...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
4,Business Analyst (Banking)\n- job post,JONDAVIDSON PTE. LTD.,"$4,500 - $9,000 a month - Full-time",NaN,Singapore,Collate and manage all the details regarding t...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
...,...,...,...,...,...,...,...,...,...,...
310,Full Stack Engineer\n- job post,WHITECOAT HOLDINGS PTE. LTD.,"$5,000 - $8,000 a month - Full-time",NaN,Singapore,Position Overview:\nWe are looking for a passi...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
311,Software Developer\n- job post,Dayforce,Full-time,NaN,Singapore•Hybrid work,Dayforce is a global human capital management ...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
312,Junior Software Developer\n- job post,Flintex Consulting Pte Ltd,"$5,000 - $8,500 a month",NaN,Singapore 079903,Job Responsibilities\n\n\nWorks with multi-dis...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
313,Frontend Engineer\n- job post,CEDARS DIGITAL PTE. LTD.,"$4,000 - $8,000 a month - Permanent, Full-time",NaN,Singapore,Want to be a part of the fastest growing start...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
314,Robot Software Engineer / Developer\n- job post,MYRMIDON LABORATORIES PTE. LTD.,"$3,500 - $7,000 a month - Full-time",NaN,Singapore,About MyrLabs\nMyrLabs is an A*STAR spin-off t...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...

In [35]:
# Remove additional text of -job post in Job Title Col
for index, row in data.iterrows():
    parts = row['Job Title'].split('-', 1)
    data.loc[index, 'Job Title'] = parts [0]

data

,Job Title,Company,Salary,Job Type,Location,Job Description,Posted Date Raw,Today Date,Job Posting Date,URL
0,Business Analyst\n,EMQ2 TECHNOLOGY SERVICES PTE. LTD.,"$5,400 - $7,500 a month - Full-time",NaN,Singapore,Main Activities and Tasks\nOrganize and facili...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
1,Business Analyst\n,ITCAN PTE. LIMITED,"$5,000 - $7,000 a month - Full-time",NaN,Singapore,Mandatory Skills Overview: As a Business Analy...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
2,Business Analyst\n,TECHNOPALS CONSULTANTS PTE. LTD.,"$6,000 - $7,500 a month - Contract",NaN,Singapore,Mandatory Skills\nOverview :\nAs a Business An...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
3,Business Analyst |Up to $9500 |East\n,JULIAN GREY CORPORATE ADVISORY PTE. LTD.,"$7,000 - $9,500 a month - Permanent, Full-time",NaN,Singapore,Company’s Profile\nJulian Grey’s client is a s...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
4,Business Analyst (Banking)\n,JONDAVIDSON PTE. LTD.,"$4,500 - $9,000 a month - Full-time",NaN,Singapore,Collate and manage all the details regarding t...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
...,...,...,...,...,...,...,...,...,...,...
310,Full Stack Engineer\n,WHITECOAT HOLDINGS PTE. LTD.,"$5,000 - $8,000 a month - Full-time",NaN,Singapore,Position Overview:\nWe are looking for a passi...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
311,Software Developer\n,Dayforce,Full-time,NaN,Singapore•Hybrid work,Dayforce is a global human capital management ...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
312,Junior Software Developer\n,Flintex Consulting Pte Ltd,"$5,000 - $8,500 a month",NaN,Singapore 079903,Job Responsibilities\n\n\nWorks with multi-dis...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
313,Frontend Engineer\n,CEDARS DIGITAL PTE. LTD.,"$4,000 - $8,000 a month - Permanent, Full-time",NaN,Singapore,Want to be a part of the fastest growing start...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
314,Robot Software Engineer / Developer\n,MYRMIDON LABORATORIES PTE. LTD.,"$3,500 - $7,000 a month - Full-time",NaN,Singapore,About MyrLabs\nMyrLabs is an A*STAR spin-off t...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...

In [36]:
# To seperate the salary and Job Type during web scraping
for index, row in data.iterrows():
    if row['Salary'] == "nan":
        pass
    elif '$' not in str(row['Salary']):
        data.loc[index, 'Job Type'] = row['Salary']
        data.loc[index, 'Salary'] = None
    elif "Up to" in row['Salary'] and row['Salary'].count('-') >= 1:
        parts = row['Salary'].split('-', 1)
        data.loc[index, 'Salary'] = parts[0] 
        data.loc[index, 'Job Type'] = parts[1]
    elif row['Salary'].count('-') >= 2:
        parts = row['Salary'].split('-', 2)
        data.loc[index, 'Salary'] = parts[0] + '-' + parts[1]
        data.loc[index, 'Job Type'] = parts[2]

data

/var/folders/fv/74lzq5vn7k567r8ld9jjbqxw0000gn/T/ipykernel_63504/1667469387.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' Full-time' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[index, 'Job Type'] = parts[2]

,Job Title,Company,Salary,Job Type,Location,Job Description,Posted Date Raw,Today Date,Job Posting Date,URL
0,Business Analyst\n,EMQ2 TECHNOLOGY SERVICES PTE. LTD.,"$5,400 - $7,500 a month",Full-time,Singapore,Main Activities and Tasks\nOrganize and facili...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
1,Business Analyst\n,ITCAN PTE. LIMITED,"$5,000 - $7,000 a month",Full-time,Singapore,Mandatory Skills Overview: As a Business Analy...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
2,Business Analyst\n,TECHNOPALS CONSULTANTS PTE. LTD.,"$6,000 - $7,500 a month",Contract,Singapore,Mandatory Skills\nOverview :\nAs a Business An...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
3,Business Analyst |Up to $9500 |East\n,JULIAN GREY CORPORATE ADVISORY PTE. LTD.,"$7,000 - $9,500 a month","Permanent, Full-time",Singapore,Company’s Profile\nJulian Grey’s client is a s...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
4,Business Analyst (Banking)\n,JONDAVIDSON PTE. LTD.,"$4,500 - $9,000 a month",Full-time,Singapore,Collate and manage all the details regarding t...,PostedToday,10/04/2024,NaN,https://sg.indeed.com/jobs?q=business+analyst&...
...,...,...,...,...,...,...,...,...,...,...
310,Full Stack Engineer\n,WHITECOAT HOLDINGS PTE. LTD.,"$5,000 - $8,000 a month",Full-time,Singapore,Position Overview:\nWe are looking for a passi...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
311,Software Developer\n,Dayforce,None,Full-time,Singapore•Hybrid work,Dayforce is a global human capital management ...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
312,Junior Software Developer\n,Flintex Consulting Pte Ltd,"$5,000 - $8,500 a month",NaN,Singapore 079903,Job Responsibilities\n\n\nWorks with multi-dis...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
313,Frontend Engineer\n,CEDARS DIGITAL PTE. LTD.,"$4,000 - $8,000 a month","Permanent, Full-time",Singapore,Want to be a part of the fastest growing start...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...
314,Robot Software Engineer / Developer\n,MYRMIDON LABORATORIES PTE. LTD.,"$3,500 - $7,000 a month",Full-time,Singapore,About MyrLabs\nMyrLabs is an A*STAR spin-off t...,PostedPosted 1 day ago,10/04/2024,NaN,https://sg.indeed.com/jobs?q=software+engineer...

In [47]:
# To indicate the listing date from posted date information
import re
from datetime import datetime, timedelta

# Convert text to datetime for manipulation 
data['Today Date'] = pd.to_datetime(data['Today Date'], format='%d/%m/%Y')

# Convert 'Today Date' to string with 'day/month/year' format
data['Today Date'] = data['Today Date'].dt.strftime('%d/%m/%Y')

for index, row in data.iterrows():
    if not re.search(r'\d', row['Posted Date Raw']):
        data.loc[index, 'Job Posting Date'] = row['Today Date']
    else:
        days = re.findall(r'\d+', row['Posted Date Raw'])
        days_int = sum(map(int, days))
        listing_date = pd.to_datetime(row['Today Date'], format='%d/%m/%Y') - pd.DateOffset(days=days_int)
        data.loc[index, 'Job Posting Date'] = listing_date.strftime('%d %B %Y')  # Change the format here

# Convert 'Job Posting Date' column to datetime dtype
data['Job Posting Date'] = pd.to_datetime(data['Job Posting Date'], format='%d %B %Y')

data

,Job Title,Company,Salary,Job Type,Location,Job Description,Posted Date Raw,Today Date,Job Posting Date,URL
0,Business Analyst\n,EMQ2 TECHNOLOGY SERVICES PTE. LTD.,"$5,400 - $7,500 a month",Full-time,Singapore,Main Activities and Tasks\nOrganize and facili...,PostedToday,10/04/2024,2024-10-04,https://sg.indeed.com/jobs?q=business+analyst&...
1,Business Analyst\n,ITCAN PTE. LIMITED,"$5,000 - $7,000 a month",Full-time,Singapore,Mandatory Skills Overview: As a Business Analy...,PostedToday,10/04/2024,2024-10-04,https://sg.indeed.com/jobs?q=business+analyst&...
2,Business Analyst\n,TECHNOPALS CONSULTANTS PTE. LTD.,"$6,000 - $7,500 a month",Contract,Singapore,Mandatory Skills\nOverview :\nAs a Business An...,PostedToday,10/04/2024,2024-10-04,https://sg.indeed.com/jobs?q=business+analyst&...
3,Business Analyst |Up to $9500 |East\n,JULIAN GREY CORPORATE ADVISORY PTE. LTD.,"$7,000 - $9,500 a month","Permanent, Full-time",Singapore,Company’s Profile\nJulian Grey’s client is a s...,PostedToday,10/04/2024,2024-10-04,https://sg.indeed.com/jobs?q=business+analyst&...
4,Business Analyst (Banking)\n,JONDAVIDSON PTE. LTD.,"$4,500 - $9,000 a month",Full-time,Singapore,Collate and manage all the details regarding t...,PostedToday,10/04/2024,2024-10-04,https://sg.indeed.com/jobs?q=business+analyst&...
...,...,...,...,...,...,...,...,...,...,...
310,Full Stack Engineer\n,WHITECOAT HOLDINGS PTE. LTD.,"$5,000 - $8,000 a month",Full-time,Singapore,Position Overview:\nWe are looking for a passi...,PostedPosted 1 day ago,10/04/2024,2024-04-09,https://sg.indeed.com/jobs?q=software+engineer...
311,Software Developer\n,Dayforce,None,Full-time,Singapore•Hybrid work,Dayforce is a global human capital management ...,PostedPosted 1 day ago,10/04/2024,2024-04-09,https://sg.indeed.com/jobs?q=software+engineer...
312,Junior Software Developer\n,Flintex Consulting Pte Ltd,"$5,000 - $8,500 a month",NaN,Singapore 079903,Job Responsibilities\n\n\nWorks with multi-dis...,PostedPosted 1 day ago,10/04/2024,2024-04-09,https://sg.indeed.com/jobs?q=software+engineer...
313,Frontend Engineer\n,CEDARS DIGITAL PTE. LTD.,"$4,000 - $8,000 a month","Permanent, Full-time",Singapore,Want to be a part of the fastest growing start...,PostedPosted 1 day ago,10/04/2024,2024-04-09,https://sg.indeed.com/jobs?q=software+engineer...
314,Robot Software Engineer / Developer\n,MYRMIDON LABORATORIES PTE. LTD.,"$3,500 - $7,000 a month",Full-time,Singapore,About MyrLabs\nMyrLabs is an A*STAR spin-off t...,PostedPosted 1 day ago,10/04/2024,2024-04-09,https://sg.indeed.com/jobs?q=software+engineer...

In [48]:
data.to_csv('indeed_jobs_modified.csv', index=False)